### ISSUE TITLE
Feedback for “What is Tapicker? | Tapicker”

### ISSUE THREAD

**Issue by Zxk6699** [ibyetool/tapicker-docs#1]
Hello, I have a few questions to ask
1: When collecting pictures, can you change it to the URL address for collecting large pictures? At present, all the collected pictures are thumbnail addresses, not large pictures.
2: How to set the collection configuration so that the collected data can form a table
3: I need to know how to get feedback on the problems I send

**Comment by ibyetool** [comment]
@Zxk6699 Hi ~ Give me an example please. Which page do you want to scrape data from? I can assist you in creating a recipe.

And some video tutorials here, maybe useful for you. [video-tutorial](https://docs.tapicker.com/docs/video-tutorial)

**Comment by Zxk6699** [comment]
Hello team,


Please assist me to do the listing collection from platform 1688.com ( please collect the listing with pages&nbsp; by keywords. Procedure should be : 1. click on the sku link, and this sku has variant, the information I need will be product name, description, price, sku id(you can get this id from the page), seller name, image( I need big image, and good resolution image, usually should be at least 800x800, kindly support this).
amazon.com ( i need product name, product price, and product description)
and there are also other platforms, which i can prodvide to you as well. Hence, could you please arrange the receipt for me ?



Thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ibyetool/tapicker-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月16日(星期三) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ibyetool/tapicker-docs] Feedback for “What is Tapicker? | Tapicker” (Issue #1)





 
@Zxk6699 Hi ~ Give me an example please. Which page do you want to scrape data from? I can assist you in creating a recipe.
 
And some video tutorials here, maybe useful for you. video-tutorial

**Comment by ibyetool** [comment]
@Zxk6699 You can join our TG group or QQ group for better communication online.

TG group: [https://t.me/+x8YG9CreBzZmYTZl](https://t.me/+x8YG9CreBzZmYTZl)
QQ group: 690680164
